---
- name: Prepare host
  include_tasks: prepare_host.yml

- name: Install i2p
  include_tasks: install.yml

- name: Configure i2p
  include_tasks: configure.yml

# - name: Start and enable i2p router
#   service:
#     name: "i2p"
#     state: started
#     enabled: true
