---
- name: Prepare host
  ansible.builtin.include_tasks: prepare_host.yml

- name: Install i2p
  ansible.builtin.include_tasks: install.yml

- name: Configure i2p
  ansible.builtin.include_tasks: configure.yml

# - name: Start and enable i2p router
#   ansible.builtin.systemd_service:
#     name: "i2p"
#     state: started
#     enabled: true
