---
- name: Install dependencies
  apt:
    pkg: "{{ i2p_package_dependencies | list }}"

- name: Make unix group
  ansible.builtin.group:
    name: "{{ i2p_unix_group }}"
    state: present

- name: Make unix user
  ansible.builtin.user:
    name: "{{ i2p_unix_user }}"
    group: "{{ i2p_unix_group }}"
    state: present
    shell: "/bin/false"
    home: "{{ i2p_unix_home }}"
